version: '3.8'

services:
  task-marshal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-marshal
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - PORT=3000
      - DATABASE_URL=sqlite:./data/task-marshal.db
      - RBAC_ENABLED=true
      - AUDIT_ENABLED=true
      - TENANT_ISOLATION_ENABLED=true
      - AI_ENABLED=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  task-marshal-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: task-marshal-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=3000
      - DATABASE_URL=sqlite:./data/task-marshal-dev.db
      - RBAC_ENABLED=true
      - AUDIT_ENABLED=true
      - TENANT_ISOLATION_ENABLED=true
      - AI_ENABLED=true
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - dev
