name: Debug Publishing

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Debug npm configuration
        run: |
          echo "=== NPM Configuration ==="
          npm config list
          echo ""
          echo "=== Package Info ==="
          node -p "require('./package.json').name"
          node -p "require('./package.json').version"
          echo ""
          echo "=== NPM Token Check ==="
          if [ -n "$NPM_TOKEN" ]; then
            echo "NPM_TOKEN is set (length: ${#NPM_TOKEN})"
          else
            echo "NPM_TOKEN is not set"
          fi
          echo ""
          echo "=== Registry Check ==="
          npm config get registry
          echo ""
          echo "=== Whoami Check ==="
          npm whoami --registry=https://registry.npmjs.org || echo "npm whoami failed"

      - name: Test npm view
        run: |
          echo "=== Testing npm view ==="
          npm view @buildworksai/task-marshal version --registry=https://registry.npmjs.org || echo "npm view failed"

      - name: Test npm publish (dry run)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "=== Testing npm publish (dry run) ==="
          if [ -f .npmrc ]; then
            rm .npmrc
          fi
          npm publish --dry-run --registry=https://registry.npmjs.org --access public || echo "npm publish dry run failed"
